- tutorials/creating_ssl_certificates.md
Seeing as the rest of the documentation revolves around the usage of apt instead of apt-get the SSL certificate bit should as well.
> Fixing documentation error

- daemon/upgrading.md
I just fixed a typo on the "Upgrading" page for the daemon.
> Fix typo (0.6.S to 0.6.X)

- daemon/installing.md
Same as #45 
Daemon-reloading should be unnecessary and enable --now enables & starts a service.
> Remove unnecessary commands

- daemon/installing.md
gcc-g++ isn't a valid package on CentOS, gcc-c++
> Fixed dependencies

- daemon/kernel_modifications.md
Instead of setting permissions, rename the file so it'll get detected last during update-grub.
> Rename OVHkernel file

- community/install/panel/centos7.md
- community/install/panel/debian9.md
- community/install/panel/ubuntu1804.md
corrected the php7.2-fpm service for ubuntu and debian
fixed spelling for "configuration" for centos and debian
> Update service name and fix spelling in community section

- community/install/panel/centos7.md
The instructions about where the contents described should be placed were not clear, leading to error 403 at the end of the installation.
> Update CentOS 7 tutorial

- .vuepress/config.js
- community/minecraft/networks.md
This adds the guide on bungeecord networks from the deprecated readme.io community guides as it comes up rather frequently.
I've also added a section regarding ufw on ubuntu which causes issues quite often.
Do we want to have game specific sections in the community part of the docs or should we organise that differently?
> add minecraft server networks to community section

- panel/getting_started.md
Unless I missed it, I did not see any documentation on telling the user to enable this server. Typically if someone doesn't know they should do this, then they most likely won't. Failing to run this command has caused a lot of unneeded issues due to the panel not being able to fetch the eggs since the redis-server isn't running.
> Start redis server on boot

- panel/getting_started.md
- panel/webserver_configuration.md
It seems to be a weekly issue that for people with Apache, they have issues installing the panel because they follow the tutorial and then when they view it, it's displaying the actual PHP code. The notice I've inserted will help make users aware that when using Apache, they need to specific package for Apache that will make PHP run properly.
> Clarify something for Apache

- panel/getting_started.md
Mysql version 8.x isn't supported so `or higher` shouldn't be there, as it implies MySQL 8 is supported.
> Remove `or higher` from mysql

- panel/getting_started.md
Debian 8 is starting to fall behind and not get updates. this is to call out that some modifications may be required.
> update debian 8 support status

- community/installation-guides/panel/centos7.md
Unzip is required later on when using composer. Otherwise composer will issue a warning that unzip should be installed.
> Add unzip to fix composer for centos

- community/installation-guides/panel/centos7.md
Installing certbot at this point is redundant, because it is referred to later on anyways by linking to /tutorials/creating_ssl_certificates.html where the user can choose whether to use cerbot or a different tool
> Remove redundant instructions to install certbot

- community/installation-guides/daemon/debian9.md
- daemon/installing.md
mmmagic fails to build without python-dev installed on Debian 9. It's not installed by default on OVH atleast.
> Add python-dev packages

- daemon/installing.md
Title says it all. I noticed it got removed in https://github.com/pterodactyl/documentation/commit/97e2264715a80f19ccb150d9df20104813361009
> Add Ubuntu 18.04 back

- panel/getting_started.md
new PR as i dont want to mess up the history, this does the same as https://github.com/pterodactyl/documentation/pull/100
Basically making sure that redis is started before we get all sorts of errors from people where redis wasnt on (offline is the default)
> now start redis correctly

- community/installation-guides/panel/debian9.md
- community/installation-guides/panel/ubuntu1804.md
At the end of this community guide, it normally redirects the user to install the panel first, before downloading the files for it.
Changed from #installation to #download-files
> Link user to download files first [Master]

- community/games/minecraft.md
This adds commands for CentOS' firewalld to allow inter-container communication.
This also adds new tips and warnings.
> update minecraft proxy docs.

- .vuepress/config.js
This makes more sense in my opinion. The menu item contains all documentation, not only the getting started guide.
The "Get Started" Button on the landing page will remain.
> Rename 'Get Started' to 'Documentation' in menu

- daemon/configuration.md
There is a missing option when defing a private registry in the config
https://github.com/pterodactyl/daemon/blob/b902cde7157e7cdd6b7a0a652db6840c3e766bbf/src/helpers/image.js#L75
> Add missing config to docker registry page.

- .github/workflows/github-pages.yml
@DaneEveritt please create a ssh deploy key as explained [here](https://github.com/peaceiris/actions-gh-pages#1-add-ssh-deploy-key) before merging.
resolves #142
> Use deploy key for github-pages workflow

- .snippets/webservers/nginx-php7.3.conf
- community/installation-guides/panel/debian9.md
The guide was updated to use php7.3 but pulled the default nginx config, this should solve 502's for D9 users following the community guide
> Fixed D9 php fpm issues

- community/installation-guides/panel/debian10.md
supersedes #151 #154 and #156
No extra repos are needed thus removing them
Changes the Debian 9 to Debian 10
> update debian 10 install guide

- daemon/kernel_modifications.md
Sometimes, for whatever reason, OVH sets the server's booting option to network boot, which will force the server to boot into a OVH customised kernel. I added a section about this.
I have a question: *why* are we suggesting the users to switch from a OVH customised kernel? Is it because the virtualization purposes?
> Kernel Modifications - Boot from hard disk

- community/installation-guides/daemon/debian10.md
Installing both nodejs and npm causes dependency errors. Just installing nodejs pulls in the correct npm version automagically.
```The following packages have unmet dependencies:
nodejs : Conflicts: npm
npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.```
> Resolve dependency errors

- daemon/installing.md
This adds the `--no-audit` and  `--unsafe-perm` flags so it actually installs properly as root.
> add npm flags to keep it from erroring

- panel/configuration.md
For many web services (especially less complex ones), an NGINX reverse proxy does not need the config shown in this commit, so it is reasonable to assume that many users will be unaware of this config even if they already use NGINX as a reverse proxy. Since reverse proxy configuration is discussed, it only makes sense to mention everything that Pterodactyl requires. This config might be able to be trimmed down a little bit, but I personally do not have the time to test the importance of each line individually.
> Mention additional NGINX reverse proxy config

- community/tutorials/custom_theme_setup.md
With the leading /, the path is interpreted as absolute so will attempt to load theme resources from `http://themes/<themename>/resource`. After removing this leading / themes can be created successfully.
> Fix suggested assets path in theme setup docs

- daemon/0.6/installing.md
- panel/0.7/getting_started.md
- panel/1.0/getting_started.md
- project/introduction.md
- wings/1.0/installing.md
Updated Supported Systems table for all the installs so they all match.
Removed 14.04/16.06
Removed REHL/Alpine/Fedora
Removed old versions of Debian/CentOS
Added newer versions of Debian/CentOS
Added Ubuntu 20.04
Removed the duplicate supported game, Terraria
Remade PR of #199.... The proper way...
> Updated supproted systems

- community/installation-guides/daemon/centos7.md
- community/installation-guides/daemon/centos8.md
- community/installation-guides/daemon/debian10.md
- community/installation-guides/daemon/debian9.md
- community/installation-guides/daemon/ubuntu1804.md
- community/installation-guides/daemon/ubuntu2004.md
- community/installation-guides/panel/centos7.md
- community/installation-guides/panel/centos8.md
- community/installation-guides/panel/debian10.md
- community/installation-guides/panel/debian9.md
- community/installation-guides/panel/ubuntu1804.md
- community/installation-guides/panel/ubuntu2004.md
- daemon/0.6/installing.md
- panel/0.7/getting_started.md
Added links to OS versions to show the community guide that's specific to that OS and version.
Community guides now state they're for v0.7, I'm sure they would work for v1.0 but they should be tested to make sure.
> Add links to community guides for supported os table, uniformity changes within community guides.

- .vuepress/config.js
- community/about.md
this just adds a link to the community guides section in the tutorials section of the main project page.
> add community guides to tutorial section

- .snippets/webservers/nginx-nossl.conf
- .snippets/webservers/nginx.conf
- panel/0.7/webserver_configuration.md
I think this change will help people not running into problems when certain parts of the documentation are refering to php7.2 and others to php7.3 or php7.4.
> Variable <phpversion> for 'fastcgi_pass' in webserver config

- daemon/0.6/installing.md
Removes the warning that should've been removed when forever was removed. Nobody should be using Ubuntu 14....
> Remove Ubuntu 14 warning about forever

- daemon/0.6/installing.md
Due to the new command change 'npm install --only=production --no-audit --unsafe-perm' instead of 'npm install --only=production', and due to the ``--no-audit' flag, the warning isn't needed.
> Remove 'warning Audit Results' warning.

- panel/1.0/upgrade/1.0.md
structure of the .tar.gz changed to stripping the first folder results in it getting puked everywhere...
Updates were previously in a folder of `panel-1.0.0-beta.#` now they're not, so stripping the first dir is no longer required
> Remove strip-componets from tar

- panel/0.7/getting_started.md
- tutorials/mysql_setup.md
More recent versions of MariaDB/MySQL do not use mysql_native_password as the default authentication plugin.
This will result in an authentication error (unknown authentication type) when trying to connect to the host.
Edit:
Updated MySQL/Maria documentation since the usage of `my.cnf` has changed and the default configuration files have moved for both Maria (50-server.cnf) and MySQL (mysqld.cnf)
> Update MySQL documentation

- tutorials/creating_ssl_certificates.md
Wtf is a "Glocal"?
For clarity; Fix typo "Glocal" to "Global"
> fix TYPO in ssl doc

- daemon/0.6/installing.md
Add warning on the daemon install page so that new users know to only install wings with 1.0+
To be clear, I don't know exactly how this doc software works, so let me know if I did this wrong.
> Add warning to daemon page

- panel/1.0/upgrade/1.0.md
In https://github.com/pterodactyl/documentation/commit/c300dbe640e5fee5e14f27a1c5bd6334a4faf91f the other command was removed, it's observed that adding the `--force` does both of these commands. This simply updates the string to follow suit.
> Remove Plural

- panel/0.7/getting_started.md
Been seeing many `undefined index: name` errors that could be quickly solved by adding this. yes, 0.7 deprecated, but there are many that install it anyway. let's save the headache. (inspiration from a pin in the discord)
> Specify 0.7 composer version

- panel/1.0/upgrade/0.7_to_1.0.md
Users keep complaining about artisan errors because they're executing them in the wrong folder.
This adds a notice to inform them to perform these commands inside /var/www/pterodactyl
> Notice of being in the correct folder

- tutorials/creating_ssl_certificates.md
the repository is not needed for 20.04 or 18.04 from what i see, and it doesnt work on 20.04 anyway.
> remove certbot ppa

- panel/0.7/getting_started.md
- panel/1.0/getting_started.md
Fixes #210
Adds a link at the bottom of the getting started page for the panel (1.0 and 0.7) so dummies don't miss a necessary step.
> Add Next Step to getting started

- panel/1.0/getting_started.md
- panel/1.0/upgrade/0.7_to_1.0.md
- panel/1.0/upgrade/1.0.md
- wings/1.0/installing.md
- wings/1.0/migrating.md
- wings/1.0/upgrading.md
Instead of using the version in the link use latest, makes it easier for those who use scripts to install/update panel/wings
> Fix in links

- panel/1.0/webserver_configuration.md
fixes #245
Make webserver conf file instructions a bit more clear by rewording and adding punctuation
> Make webserver conf file instructions a bit more clear

- community/config/eggs/creating_a_custom_egg.md
This would be useful for new users that are looking into creating their custom eggs, as only three variables are documented anywhere on the panel itself.
> Add default egg variable list

- .vuepress/config.js
- .vuepress/theme/VersionSelectItem.vue
Make it so that wings and panel show 1.2 in the sidebar without destroying every link out there :)
Also made the old daemon collapsable so to minimize its footprint without outright removing it
as a side note:
package-lock.json changed... am I meant to include that?
gitpod also generated a .gitpod.yml, wasn't sure if I should include that either, so I left them out for now. can add the changes if asked
> Show versions separately :O

- community/customization/panel.md
The default yarn package installation on Debian will install test scenario cmdtest instead of yarn. Using npm for the installation ensures that the actual yarn is installed, alternatively, the source list could be added for the package installer, but npm is more user-friendly. A lot of users have encountered this issue in the Discord server.
Also, increased the nodejs install version to 14, but could revert it if required.
> Fix cmdtest being installed instead of yarn

- guides/php_upgrade.md
Fixed a typo, line 54: `a2enmod` was referring to a2dismod in the comment, which is incorrect.
> Fixed a typo

- guides/php_upgrade.md
Users should have added this during their first installation of the panel, but based on so many errors from Discord, not everyone has done it.
This would reduce the unnecessary error posts on Discord about unable to locate PHP 8 packages.
> Add PHP repository during PHP upgrade

- community/config/nodes/add_node.md
There were still links leading to 404 pages (old daemon tutorials). I have changed these to the wings equivalent.
> Changed daemon references to wings

- wings/1.0/installing.md
This commit ensures that the `wings.service` only ever runs when the `docker.service` runs. This is important as the wings daemon severely misbehaves when the docker daemon is not running.
`Requires` makes sure that when `wings.service` is started that `docker.service` is started as well.  
`PartOf` makes sure that when `docker.service` is stopped (for any reason) or restarted, the same happens to `wings.service`
This change is introduced as restarting the docker daemon (for example during an update of docker) causes the wings daemon to enter a broken state, that consumes high amount of CPU and doesn't properly interact with the containers anymore. It never recovers from that state by itself, even after the docker daemon comes back up again. Only way I've found to fix that is by …
> Configure a stronger dependency on docker.service in the service file

- wings/1.0/configuration.md
Resolves errors about not finding the pterodactyl network after it's been changed to host.
`Error response from daemon: network pterodactyl_nw not found`
> add network_mode: host

- panel/1.0/webserver_configuration.md
Some users appear to be missing that you actually need to install Wings and not just the Panel. This would make it a complete flow of Panel installation > webserver configuration > Wings installation
> Add Wings to the chronological next step

- community/config/eggs/creating_a_custom_egg.md
While reading the doc, I found out that there's five parsers other than the file one, not four.
> Fixed a grammar issue

- wings/1.0/installing.md
This is no longer relevant with Wings and is leftover from the old daemon
> Remove instructions to navigate into a directory to start wings

- panel/1.0/updating.md
A lot of support requests in Discord are coming from users performing the upgrade in the wrong directory. I moved it outside the text block to make it more visible, together with adding the self-upgrade command option.
> Add self-upgrade and more clear notice of being in the correct folder

- wings/1.0/configuration.md
Someone had an issue with startup hanging on checking permissions and wasn't able to find how to disable it
> Include check_permissions_on_boot in the additional configuration

- tutorials/mysql_setup.md
Explaining why the MySQL/MariaDB changed configuration files is unnecessary in a quick skim to get the user started using the database. This tends to confuse users and make them use the old methods instead, as seen on Discord.
Asking where my.cnf file located is an extremely common question. Unfortunately, find command would miss `~/.my.cnf` location that I doubt anyone would have if they follow the documentation. Using `mysql --help | grep /my.cnf | xargs ls` would resolve this, but I fear file not found errors will mislead people.
> Clear up the database host external access

- community/tutorials/artisan.md
I remove the server:rebuild command because it’s not longer working in 1.4+
> Remove the server:rebuild command

- community/installation-guides/wings/centos7.md
- community/installation-guides/wings/centos8.md
- community/installation-guides/wings/debian10.md
- community/installation-guides/wings/debian9.md
- community/installation-guides/wings/ubuntu1804.md
- community/installation-guides/wings/ubuntu2004.md
All of the wings community guides don't have the correct link at the end.
> Fix url at the end of wings community guide

- panel/1.0/getting_started.md
- wings/1.0/installing.md
There is a chance, that e.g. the database server of the system is not yet running after any reboot. Without the `RestartSec=` option systemd will restart the service with an delay of just `100ms` for `DefaultStartLimitBurst` in an interval of `DefaultStartLimitIntervalSec`. This may also fail as the database could take a little bit longer. In that case the startup of the service is aborted and the queue worker dies silently.
Using this option (set to `30s`) should slow down this behavior and also prevent systemd of giving the service up.
I've also extended the wings service, as it seems also to be affected slow database startups (when the respective host is simultaneously (re-)starting).
> Added restart delay for pteroq and wings service

- community/installation-guides/panel/debian10.md
Personally, this is the only way I can get PHP installed nowadays. Used to work fine the old way before PHP 8 came out but now it just gives me the error php modules are not found and this fixes it for me.
> PHP Repo Debian 10 Change

- community/installation-guides/panel/ubuntu2004.md
Modify community guide for Ubuntu 20.04 to install PHP8.0
> Change Ubuntu 20.04 guide to install php8.0

- tutorials/mysql_setup.md
https://mariadb.com/kb/en/create-user/:
```
For each account, CREATE USER creates a new row in mysql.user (until MariaDB
10.3 this is a table, from MariaDB 10.4 it's a view) or mysql.global_priv_table
(from MariaDB 10.4) that has no privileges.
```
https://dev.mysql.com/doc/refman/8.0/en/create-user.html#create-user-overview:
```
For each account, CREATE USER creates a new row in the mysql.user system table.
```
Follow-up to https://github.com/pterodactyl/documentation/pull/393
> Remove unnecessary `USE mysql;` statements

- tutorials/creating_ssl_certificates.md
The row "acme.sh --issue --standalone -d "example.com" --dns dns_cf \" should be changed to "acme.sh --issue --dns dns_cf -d "example.com" \" otherwise it wont use DNS and it will require port 80 to be open.
> acme.sh command is wrong and doesn't work with DNS

- panel/1.0/additional_configuration.md
Specific configurations, such as dual-stacks or "older URLs" like minio, might require path style with the bucket being in the file path.
> docs(s3): add aws_use_path_style_endpoint

- panel/1.0/webserver_configuration.md
Many users forget to delete the default config and then ask on the Discord for help. Seems like the big red "DANGER" at the top isn't explicit enough.
> Explicitly tell to delete default webserver config

- wings/1.0/installing.md
- wings/1.0/upgrading.md
Often people with arm64 don't realize that they have to download the arm variant of wings because it is nowhere noted.
> docs(wings): Display ARM64 download for wings

- panel/1.0/additional_configuration.md
"If users have trouble logging in, or your Panel isn't exposed to the internet, in can make sense to disable reCAPTCHA."
This sentence is grammatically incorrect, it looks like "it" was misspelt as "in".
> Fix recaptcha docs typo

- panel/1.0/updating.md
Provide instructions to check composer version and a note for php-posix requirement for self-upgrade.
Some users skip or are unaware of this causing them issues during dependency installation or self-upgrade.
> display note for php-posix and composer v2

- panel/1.0/webserver_configuration.md
Many instructions require elevated privileges and most properly have `sudo` shown. Some, even in the same code block, do not. Suggest adding `sudo` to these sections so the instructions are consistent.
> docs: improve sudo consistency in web configuration

- .vuepress/config.js
Official documentation works for all Ubuntu LTS distros. There's no reason to have Ubuntu guides in different places, especially with the community guide being outdated and confusing users.
> docs(community): hide ubuntu specific guides from the sidebar

- community/installation-guides/panel/centos7.md
- community/installation-guides/panel/centos8.md
- panel/1.0/getting_started.md
- wings/1.0/installing.md
Update Remi to 9 and use PHP 8.0
Also noted that CentOS 8 is EOL.
> Update remi & use php 8 on CentOS

- panel/1.0/webserver_configuration.md
Running `a2enmod ssl` will prevent the following error that often people on the discord have:
`Invalid command 'SSLEngine', perhaps misspelled or defined by a module not included in the server configuration`
> docs: instruct to enable ssl module for apache

- .snippets/webservers/nginx-php8.1-nossl.conf
- .snippets/webservers/nginx-php8.1.conf
- .vuepress/config.js
- guides/php_upgrade.md
- panel/1.0/getting_started.md
- panel/1.0/legacy_upgrade.md
- panel/1.0/updating.md
- panel/1.0/webserver_configuration.md
- wings/1.0/upgrading.md
Add Ubuntu 22.04 to the Guide
Use official Redis PPA, which supports all of the supported Ubuntu/Debian versions.
Use PHP 8.1, which for newer distro sources will be the default on apt upgrade and currently causes headaches for some users
Use Pterodactyl 1.8 for the Panel version.
Tested on Ubuntu LTS releases 18, 20, and 22.
> Update documentation for 1.8 release

- panel/1.0/getting_started.md
Note, selecting 'php8.1-common' instead of 'php8.1-pdo'
Note, selecting 'php8.1-common' instead of 'php8.1-tokenizer'
php8.1-common is a meta-package that installs most of the widely used PHP extensions in one-go. It automatically installs package such as php8.1-pdo, php8.1-tokenizer among other useful extensions.
> use php8.1-common

- community/customization/panel.md
Updated guide to the NodeJS version used for production builds & updated the npm install global command since the currect usage is depracted.
> Update to required nodejs version

- tutorials/creating_ssl_certificates.md
ZeroSSL is the new default (since August 1st) but doesn't work well with cloudflare while letsencrypt does.
> Update acme documentation to use letsencrypt

- panel/1.0/getting_started.md
https://redis.io/docs/getting-started/installation/install-redis-on-linux/#install-on-ubuntudebian
> Use Redis official APT repository

- tutorials/creating_ssl_certificates.md
Add a line explaining the possible need to restart wings following a certificate renewal. This is already mentioned by the Support Bot in the Pterodactyl Discord server when linking this page, but is neglected on the page itself. Adding this line would help those who use this site as a primary resource. When I followed the steps on this page, I ran into instability with Wings as I didn't realize the certificate didn't apply automatically; having that explained here would have helped.
> Restart Wings in troubleshooting steps

- panel/1.0/additional_configuration.md
There has been a new `BACKUP_MAX_PART_SIZE` environment variable added. Also, there is a variable for the pre-signed URL lifespan that has never been documented.
This PR adds documentation about these two environment variables.
This is in companion with:
- PR: [pterodactyl/panel#4382](https://github.com/pterodactyl/panel/pull/4382)
- Issue: [pterodactyl/panel#4361](https://github.com/pterodactyl/panel/issues/4361)
**Note:** `BACKUP_MAX_PART_SIZE` is not released yet. Maybe leave this PR until the next pane lrelease.
> Document new environment variables for S3 backup

- panel/1.0/additional_configuration.md
Added description of AWS_BACKUPS_STORAGE_CLASS option. It was added in version 1.10.3 but has not been described.
> docs(s3): document storage class configuration

- community/customization/panel.md
Adds notice for building with NodeJS v15+, closes #484.
> feat(customization): include openssl-legacy-provider notice

- wings/1.0/configuration.md
Added some more info for proxying Wings FQDN through Cloudflare. This has been tested a few minutes ago and came to a conclusion that the FQDN must have the port that Cloudflare has (so HTTPS ports with caching enabled).
Tell me if anything is wrong here, I'm glad to help figure it out!
> Proxying Wings FQDN through Cloudflare

- tutorials/creating_ssl_certificates.md
Some users think that it is required to use acme when using cloudflare proxy and generating a ssl cert because of the missleading tab name.
The new name should make it clearer.
> Update tab name of acme method in ssl docs

- panel/1.0/legacy_upgrade.md
As of panel version 1.11.1, the required PHP version jumped to PHP 8.0.
> docs(legacy): Update required PHP version

- panel/1.0/updating.md
Updates the supported versions section to reflect v1.10.x of the panel (and subsequently the corresponding Wings version) as unsupported.
> chore: update supported versions

- .github/workflows/github-pages.yml
The current builds are failing because of the ssl crypto issue, this should fix it.
EDIT: it nows build the assets just fine
> Set nodejs version to 16

- tutorials/mysql_setup.md
It's better to create a separate user for the database host. The panel db user won't work as database host user anyways since it has only access to the `panel` db.
Also, most people just blindly copy and paste the commands from the docs so they would create the panel db user with `GRANT` permissions. This is not needed.
> Do not recommend to use the panel db user for a database host

- panel/1.0/getting_started.md
1. There's no colon for Apache on CentOS
2. Is there really a reason for them?
> Remove colons from Permissions

- community/config/eggs/creating_a_custom_egg.md
Fix redundant phrasing in the "Creating a Custom Egg" page.
Former: "_In this case_, the name and description speak for themselves _in this case_." (emphasis added)
Now: "In this case, the name and description speak for themselves."
> Fix typo: redundant phrasing

- community/customization/panel.md
As stated on [nodesource/distributions#readme](https://github.com/nodesource/distributions#readme):
We'd like to inform you of important changes to our distribution repository [nodesource/distributions](https://github.com/nodesource/distributions).
**What's New:**
- _**Installation Scripts:** The installation scripts `setup_XX.x` are no longer supported and are not needed anymore, as the installation process is straightforward for any RPM and DEB distro._
---
Closes #543
> Use packages for installing NodeJS instead of the installer as not supported

- .snippets/webservers/Caddyfile
- .snippets/webservers/Caddyfile-nossl
Line breaks in environment variables in caddy fpm configs don't support the \n notation.
This was causing PHP to set `upload_max_filesize` to `100M \n post_max_size = 100M`.
This lead to `upload_max_filesize` being evaluated to an invalid value that causes file uploads (such as egg imports) to fail due to the size being above `upload_max_filesize`.
This PR replaces the \n with an actual newline.
I've confirmed this works in a fresh testing environment.
> Correct caddy PHP_VALUE value as it doesn't support \n

- .vuepress/theme/Layout.vue
- .vuepress/theme/styles/sidebar.css
This removes some of the left over margins from the banner that was just removed from the website.
Right now it's an empty space that's just pushing everything down.
> Remove some left over margins from the banner that was just removed

- daemon/0.6/configuration.md
- daemon/0.6/debian_8_docker.md
- daemon/0.6/installing.md
- daemon/0.6/kernel_modifications.md
- daemon/0.6/standalone_sftp.md
- daemon/0.6/upgrade/0.4_to_0.5.md
- daemon/0.6/upgrade/0.5.md
- daemon/0.6/upgrade/0.5_to_0.6.md
- daemon/0.6/upgrade/0.6.md
- daemon/0.6/upgrading.md
- panel/0.7/configuration.md
- panel/0.7/getting_started.md
- panel/0.7/troubleshooting.md
- panel/0.7/upgrade/0.6_to_0.7.md
- panel/0.7/upgrade/0.7.md
- panel/0.7/upgrading.md
- panel/0.7/webserver_configuration.md
This is to prevent them from appearing on google search results.
They currently rank very high and are still confusing users despite the large warnings present on the pages.
Closes https://github.com/pterodactyl/documentation/issues/586
> Add noindex robots tag to old panel 0.7 and daemon 0.6 pages

- panel/1.0/troubleshooting.md
Expired certificate can create an error that looks like a general communication error, since websocket or XHR requests just fail in very similar way like the service was not responding at all.
This could be a quite common case, especially if the certificate renewal (e.g. for Let's Encrypt) is not properly set up.
> panel/1.0/troubleshooting: Add note about cert expiration

- community/installation-guides/panel/debian.md
- panel/0.7/getting_started.md
- panel/1.0/getting_started.md
Updates the MariaDB repo setup script command to match https://mariadb.com/kb/en/mariadb-package-repository-setup-and-usage/
> Update mariadb repo setup script URL

- panel/1.0/troubleshooting.md
Continuation of https://github.com/pterodactyl/documentation/pull/623
> Future proof php version in docs

- guides/php_upgrade.md
php8.3-pdo automatically resolves to php8.3-common when installed - propose bringing the documentation in line to help when troubleshooting
> Correct php8.3-pdo to php8.3-common

- guides/mounts.md
/home/container support for mounts has been available for a while now, and the section above this explicitly mentions it. This line must have been missed.
> Update outdated line
