pterodactyl/documentation

project/terms.md
(this is my first pr of pterodactyl)
=> Update terms.md - Add Nest and Egg

daemon/kernel_modifications.md
The current version doesn't have spectre/meltdown patch
=> Update kernel to latest version

daemon/installing.md
Add apt install make, gcc and g++ to the installing nodejs section
=> Add apt install make, gcc and g++

daemon/upgrade/0.5_to_0.6.md
https://i.unreliable.host/Discord_2018-08-06_17-31-47.png
=> Change 0.6.0 to 0.6.1

daemon/configuration.md
Fixes a little typo in the json
=> Fix json format

daemon/debian_8_docker.md
=> Litle change for avoid confusion in instructions

daemon/upgrade/0.5_to_0.6.md
When giving info on how to start, also give info on how to stop
=> Provide info about how to stop the daemon

tutorials/creating_ssl_certificates.md
Replacing LetsEncrypt as it is outdated.
=> Replace LetsEncrypt with Certbot

panel/getting_started.md
This should clear up where to find the documentation on setting up MySQL.
=> Provide link to MySQL page

panel/getting_started.md
systemctl enable --now <service> enables & starts a service
=> Shorten systemctl enable & start

daemon/installing.md
Added node-gyp to dependencies
=> Added node-gyp

.snippets/php-fpm/pterodactyl-centos.conf, .snippets/webservers/apache-nossl.conf, .snippets/webservers/apache.conf, .snippets/webservers/nginx-centos.conf, .snippets/webservers/nginx-nossl.conf, .vuepress/config.js, community/about.md, community/install/daemon/centos7.md, community/install/daemon/debian9.md, community/install/daemon/ubuntu1804.md, community/install/panel/centos7.md, community/install/panel/debian9.md, community/install/panel/ubuntu1804.md, daemon/configuration.md, daemon/installing.md, daemon/standalone_sftp.md, daemon/upgrade/0.5_to_0.6.md, daemon/upgrade/0.6.md, daemon/upgrading.md, package.json, panel/getting_started.md, panel/upgrade/0.6_to_0.7.md, panel/upgrade/0.7.md, panel/upgrading.md, panel/webserver_configuration.md, tutorials/creating_ssl_certificates.md, yarn.lock
Sorry Dane for the config.js mess but it was necessary for now.
Transferred guides from readme to the new docs site.
=> adding community section

panel/getting_started.md
Should be fairly self explanatory by looking at the file change.
=> Install curl before installing mysql via curl

ops/publish_release.md, panel/configuration.md, panel/troubleshooting.md, tutorials/creating_ssl_certificates.md, tutorials/mysql_setup.md
Added a troubleshooting section for installing/renewing SSL's.
Fixed spelling in a couple files.
=> Added SSL Troubleshooting & Fixed Spelling Errors

project/discord.md
I've gone ahead and modified the rules a bit:
- fixed a typo
- ran the rules through Grammarly
Note: this is my first PR, ever. Please be nice :)
=> Fixed typo in the community rules section

panel/upgrading.md
=> Change 0.7.11 to 0.7.12

panel/upgrading.md
Replaces 0.7.12 in panel/upgrading to 0.7.13 which is the latest.
=> Update to 0.7.13

panel/getting_started.md
=> Add header for adding a user

panel/getting_started.md
OCD required a extra space to make up for the codebox
=> Added space.

community/installation-guides/panel/centos7.md
/panel/getting_started.md#download-files is where the user should continue to read
=> Link to correct point in Documentation

daemon/installing.md
=> Adding Fedora 29

community/installation-guides/panel/centos7.md
Accidentally closed out the old PR.
=> update centos 7 guide for php 7.3 and selinux

community/installation-guides/daemon/debian9.md, community/installation-guides/panel/debian9.md
update for php 7.3 for the panel guide
update to node 10 for the daemon guide.
add -y to come commands that didn't have them before.
=> update debian 9 doc

.vuepress/config.js, community/installation-guides/daemon/debian10.md, community/installation-guides/panel/debian10.md
add debian 10 guides using php 7.3 and node 10.
=> Add debian 10

tutorials/mysql_setup.md
Added a guide on how to add a new database to the panel with the required user grants and info on how to fill out the panel database add form.
=> Added guide on adding a database to the panel.

community/installation-guides/daemon/debian10.md
Changed Debian 9 into Debian 10 since this is a Debian 10 guide.
=> Corrected the OS it's tailored for

panel/troubleshooting.md, tutorials/mysql_setup.md
This updates the organizaion of the mysql tutorial section
This also moves the "common problems" section to troubleshooting.
=> update mysql tutorial

daemon/installing.md
Node 10 LTS comes with NPM prepackaged and have been tested to work with Pterodactyl.
=> Update Nodejs to latest LTS version

panel/webserver_configuration.md
Fix an incorrect command usage in webserver_configuration.md that led to an unknown operation when executed.
=> Fix webserver_configuration typo

.gitignore, .vuepress/config.js, community/installation-guides/daemon/centos8.md, community/installation-guides/panel/centos8.md
This is a base install for centos 8.
Covers the Panel and Daemon.
Uses packages provided by redhat. (no extra repos other than docker.)
Many changes in CentOS 8 make this a much easier install.
=> add centos 8

community/installation-guides/panel/debian9.md
Remove mariadb repo as in repo packages are sufficient.
=> Update Debian 9 guide

panel/getting_started.md
Add Debian 10
Add CentOS 8
Note 16.04 is near EoL
=> Update Server OS table

wings/installing.md
added a line to set perms for the wings file, I was having troubles running it without setting the perms.
=> set permissions for wings file

wings/installing.md
Fixed the missing ``` for the download the daemon section.
=> Fixed formatting

panel/0.8/getting_started.md
Removed Ubuntu 14
Added Ubuntu 19.04
=> Remove U14, Add U 19

panel/troubleshooting.md
Adds a callout for dns issues on redhat based distros with firewalld.
=> add troubleshooting for firewalld

community/installation-guides/daemon/centos7.md
This is for CentOS 7 community guide.
=> Change Node.js install script from 8 to 10

.vuepress/config.js, community/installation-guides/daemon/centos7.md, community/installation-guides/daemon/centos8.md, community/installation-guides/daemon/debian10.md, community/installation-guides/daemon/debian9.md, community/installation-guides/daemon/ubuntu2004.md, community/installation-guides/panel/ubuntu2004.md
changes the community guides to specify 0.6.X versus wings.
Add Ubuntu 20.04
=> update community guides

wings/1.0/installing.md, wings/1.0/upgrading.md
Executable files don't belong into `/etc`.
I'd suggest `/usr/local/bin` instead.
=> fix wings install location

community/installation-guides/daemon/centos8.md
add firewalld commands to fix dns issues.
resolves #222
=> update centos 8 daemon guide

.vuepress/theme/styles/text.css
this was probably lost due to the tailwind upgrade.
=> make h3 and h4 a little bit bigger

.snippets/webservers/nginx-nossl.conf, .snippets/webservers/nginx.conf, panel/0.7/webserver_configuration.md
Reverts pterodactyl/documentation#230
=> Revert "Variable <phpversion> for 'fastcgi_pass' in webserver config"

community/tutorials/custom_theme_setup.md
Fixes warning box to not include the whole page.
=> Fix warning box

panel/1.0/upgrade/0.7_to_1.0.md
Removing the recursive flag to prevent damaging results.
=> Remove the recursive flag

panel/1.0/upgrade/0.7_to_1.0.md, panel/1.0/upgrade/1.0.md
Move update depends to the correct guide.
=> Move Update Depends

.vuepress/config.js, package-lock.json, package.json, wings/1.0/configuration.md, yarn.lock
=> Add Custom registries to Wings 1.0

panel/1.0/upgrade/0.7_to_1.0.md
Not sure how this looks, but we can change it again if it's unreadable 😄 
Thanks to `J0N3S#1337` for pointing this out.
=> Add hint to update nginx conf when upgrading php

panel/1.0/getting_started.md
Contextually relevent info for people who want easier setup
=> WISP Infomercial

community/installation-guides/panel/centos7.md, community/installation-guides/panel/centos8.md, community/installation-guides/panel/debian10.md, community/installation-guides/panel/debian9.md, community/installation-guides/panel/ubuntu1804.md, community/installation-guides/panel/ubuntu2004.md
Update the community guides to php 7.4, but better
=> Update to php7.4

community/installation-guides/panel/centos7.md, community/installation-guides/panel/centos8.md, community/installation-guides/panel/debian10.md, community/installation-guides/panel/debian9.md, community/installation-guides/panel/ubuntu1804.md
=> Fix community guides formatting

community/installation-guides/wings/centos7.md, community/installation-guides/wings/centos8.md, community/installation-guides/wings/debian10.md, community/installation-guides/wings/debian9.md, community/installation-guides/wings/ubuntu1804.md, community/installation-guides/wings/ubuntu2004.md
Just cleaned up things, made things more consistent, and corrected some wording
=> Clean up wings guides a bit

daemon/0.6/upgrading.md, panel/0.7/upgrading.md, panel/1.0/upgrading.md
add 1.0 upgrades to the old daemon's upgrading page
make of it what you will.
=> Add 1.0 to 0.6 upgrading.md

tutorials/creating_ssl_certificates.md
https://youtu.be/q8eUuFbAttc?t=2270
There you go :)
-- threw this together after watching the VOD, dunno if i missed something.
=> Webserver Integrated Certbot instructions

wings/1.0/migrating.md
=> Minor wording fix in Wings migration

panel/0.7/getting_started.md
=> Set composer 1.x for panel 0.7

panel/1.0/getting_started.md
Would be pretty bad if someone executed this in a different directory..
=> Replace wildcard to absolute path with wildcard

tutorials/creating_ssl_certificates.md
Changes "wont" to "won't" on the SSL cert page
=> Fix small typo

community/tutorials/custom_theme_setup.md
mainly wanted to yeet that typo, but also added a version warning since I was at it
the wording of the disclaimer could be better
=> Add disclaimer to theming page

community/config/eggs/creating_a_custom_egg.md
Idk if there should be a link to the old daemon parsing as well
=> Update link to valid parsers

wings/1.0/installing.md
Instructions on where to actually create a node and that the config file must be created, as some users tend to have issues and questions related to this topic
=> Add information about where to create a new node

panel/1.0/webserver_configuration.md
Removes duplicated Apache without ssl tab
=> Remove duplicate tab

wings/1.0/configuration.md
Ideas regarding additional Wings configurations that users tend to ask for, such as proxying through Cloudflare,  throttle limits, and enabling host mode.
=> Additional Wings Configuration

wings/1.0/configuration.md
Documents pterodactyl/wings#88
=> Added app_name

.snippets/webservers/apache.conf
Without this, access to the panel will be denied!
=> Not access to Panel

wings/1.0/configuration.md
Adds the newly introduced PID and installer limits from Wings 1.4.4
=> New PID and installer limits

.vuepress/config.js, panel/1.0/updating.md
~~Removes the `--force` flag for seeding, it will prompt them if they really wanna run that command.~~
Updates the sidebar version to 1.5 to match the version we're on.
=> Update title for sidebar

panel/1.0/additional_configuration.md
I didn't know where or how certain things were configured until I delved into the files, so I figured other people might not know as well.
=> Add info regarding backup drivers

community/installation-guides/wings/centos8.md
Fixed wording to make it unified with the Panel Documentation. Seems like the part I changed was forgotten!
=> Update centos8.md for Wings to fix wording

project/terms.md
Because some people in discord sometimes ask what a "yolk" is.
=> Add "Yolk" and "Docker image" term to terminology

wings/1.0/installing.md, wings/1.0/upgrading.md
Clarifies the need to download a different file
=> Add instructions for downloading Wings for ARM

community/tutorials/artisan.md
Adds the p:upgrade to the artisan community docs area.
=> Added p:upgrade

community/installation-guides/panel/debian10.md
Modified to install php8.0 and all it's dependencies in 8.0 (previous : 7.4)
=> Update debian10.md to install php8.0

panel/0.7/getting_started.md, tutorials/mysql_setup.md
Not necessary when using GRANT:
https://dev.mysql.com/doc/refman/8.0/en/privilege-changes.html
=> Remove 'FLUSH PRIVILEGES;' calls

wings/1.0/installing.md
Resolves https://github.com/pterodactyl/documentation/issues/397
=> Add TIP to swap limit block

wings/1.0/installing.md
Provides a more straightforward virtualization check that returns the exact virtualization type.
Adds Windows warning and fixes Kernel modification link.
Should reduce the common issues with LXC/OpenVZ and Windows.
=> A more straightforward virtualization check

panel/1.0/getting_started.md
In blue box for setting up the mysql user for the panel add the exit command so you go back to you normal shell.
=> add the exit command to the panel mysql setup.

panel/1.0/getting_started.md, wings/1.0/installing.md
=> add debian 11 to OS list

project/introduction.md
Changed PHP 7 to PHP 8 due to change on recommeneded version on installation
=> docs: update tech stack in introduction

.vuepress/config.js
=> docs: do not specify PHP 7 version in meta tag

tutorials/creating_ssl_certificates.md
Provides more information about the methods for certificate generation and renewal
resolves #458
=> docs: expand generating certificate documentation

wings/1.0/migrating.md
"Remeber" -> "Remember" in Migration to Wings documentation page
=> fix(doc): Spelling mistake

tutorials/creating_ssl_certificates.md
Cloudflare has change how token works, so we need to change the documentation accordingly.
=> Change Cloudflare acme requierements

.vuepress/theme/Home.vue
=> Change sponsor link

community/tutorials/artisan.md
=> Fixed resort typo

panel/1.0/getting_started.md
stop support for Ubuntu 18.04 as it is end of life 
https://endoflife.date/ubuntu
needs #526
=> Stop support for Ubuntu 18.04 EOL

community/installation-guides/panel/centos8.md
With this small modification Fedora Server 37 will work with this guide out of the box.
=> Fedora Server 38 Support

panel/1.0/getting_started.md
Formatting change which I didn't pick up on from #672
=> Formatting #672

wings/1.0/installing.md
Added support for Debian 13 in the installation guide.
=> Add Debian 13 support
